sudo: false
language: node_js
node_js:
  - "6"
cache:
  apt: true
  bundler: true
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_94586e9ed892_key -iv $encrypted_94586e9ed892_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
before_script:
  - git checkout $TRAVIS_BRANCH
  - bundle install
  - npm install -g grunt-cli
script:
  - sed -i s,http://wcldn-2017.dev,https://i0.wp.com/raw.githubusercontent.com/WCLDN/2017-theme/master,g src/_variables.scss
  - grunt travis
  - git checkout $TRAVIS_BRANCH src/_variables.scss
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: develop
