sudo: false
language: node_js
cache:
  apt: true
  bundler: true
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_94586e9ed892_key -iv $encrypted_94586e9ed892_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
before_script:
  - git checkout $TRAVIS_BRANCH
  - bundle install
  - npm install -g grunt-cli
script:
  - sed -i.bak s/http:\/\/wcldn-2017.dev/http:\/\/i0.wp.com\/raw.githubusercontent.com\/WCLDN\/2017-theme\/master/g src/_variables.scss
  - grunt travis
  - git checkout $TRAVIS_BRANCH src/_variables.scss
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote add deploy git@github.com:WCLDN/2017-theme.git
  - git add -f build/style.css build/style.css.map
  - 'git commit --message "[ci skip] Travis build: ${TRAVIS_BUILD_NUMBER}"'
  - git fetch deploy
  - git checkout -b master deploy/master
  - git checkout $TRAVIS_BRANCH build/style.css
  - git checkout $TRAVIS_BRANCH images
  - mv build/style.css style.css
  - git add style.css images
  - git rm --cached build/style.css
  - rm -rf build
  - 'git commit --message "[ci skip] Travis build: ${TRAVIS_BUILD_NUMBER}"'
  - git push deploy master
